- name: Alterar as unidades do systemd
  ansible.builtin.copy:
    src: etc/systemd/system/lucasbrum.service
    dest: /etc/systemd/system/lucasbrum.service
    owner: root
    group: root
    mode: "0644"

- name: Creates /etc/sudoers.d directory
  ansible.builtin.file:
    path: /etc/sudoers.d
    state: directory
    mode: "0750"

- name: >-
    Habilitar o usuario nginx para rodar:
    sudo /usr/bin/systemctl restart|stop|start|status lucasbrum,
    sem necessidade de senha
  community.general.sudoers:
    name: lucasbrum
    user: nginx
    commands:
      - /usr/bin/systemctl stop lucasbrum
      - /usr/bin/systemctl start lucasbrum
      - /usr/bin/systemctl restart lucasbrum
      - /usr/bin/systemctl status lucasbrum
    nopassword: true

- name: Reiniciar as unidades do systemd
  ansible.builtin.systemd:
    name: lucasbrum.service
    state: restarted
    enabled: true
    daemon_reload: true