set -g lock-after-time 120
set -g lock-command "cmatrix -absC blue"
set -g monitor-silence 240
set -g visual-silence off
set -g alert-silence clock
set -g silence-action current
set -g visual-bell off
set -g mouse on
setw -g xterm-keys on
set -g history-limit 30000
set -g base-index 1
set -g remain-on-exit on
setw -g remain-on-exit on
